# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Nick Weiland
tagline:             blog
url:                 http://weilandia.github.io
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nick Weiland
  url:               https://twitter.com/weilandia
  email:             nickweiland@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/weilandia/weilandia.github.io
